# Generated by Django 5.2.5 on 2025-09-03 11:57

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("place", models.CharField(max_length=255, verbose_name="Место выполнения привычки")),
                ("time", models.TimeField(verbose_name="Время выполнения привычки")),
                ("action", models.CharField(max_length=255, verbose_name="Действие привычки")),
                ("is_pleasant", models.BooleanField(default=False, verbose_name="Приятная привычка")),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("0 * * * *", "каждый час"),
                            ("0 */2 * * *", "каждые 2 часа"),
                            ("0 */3 * * *", "каждые 3 часа"),
                            ("0 9,13,18 * * *", "3 раза в день"),
                            ("0 9,18 * * *", "2 раза в день"),
                            ("0 9 * * *", "каждый день"),
                            ("0 9 */2 * *", "каждые 2 дня"),
                            ("0 9 */3 * *", "каждые 3 дня"),
                            ("0 9 * * 1,3,5", "выбранные дни"),
                        ],
                        max_length=20,
                        verbose_name="Периодичность выполнения привычки",
                    ),
                ),
                ("reward", models.CharField(blank=True, max_length=255, verbose_name="Вознаграждение")),
                (
                    "time_to_end",
                    models.DurationField(default=datetime.timedelta(seconds=120), verbose_name="Время на выполнение"),
                ),
                ("is_public", models.BooleanField(default=False, verbose_name="Публичность привычки")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_notified_on", models.DateTimeField(blank=True, null=True)),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="related_habits",
                        to="habits.habit",
                        verbose_name="Связанная привычка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
    ]
