# Generated by Django 5.2.5 on 2025-09-03 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="habit",
            name="frequency",
        ),
        migrations.AddField(
            model_name="habit",
            name="periodicity_days",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="Количество дней между выполнениями привычки (1–7)",
                verbose_name="Периодичность (в днях)",
            ),
        ),
    ]
